version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:latest
    env_file:
      - vhost.env
    volumes:
      - jenkins-data:/var/jenkins_home
      - /home/nikitamishagin/workspace:/var/jenkins_home/workspace
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
        order: start-first
      restart_policy:
        condition: on-failure

volumes:
  jenkins-data:

networks:
  default:
    external: true
    name: reverse-proxy_proxy
